### ISSUE TITLE
Deprecated YAML warning

### ISSUE THREAD

**Issue by kfindeisen** [lsst-sqre/documenteer#63]
When running `documenteer` 0.4.5 with `PyYAML` 5.1 I get the following warning:
```
lsstsw3/miniconda/envs/lsst-scipipe/lib/python3.7/site-packages/documenteer/sphinxconfig/technoteconf.py:65:
    YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  _metadata = yaml.load(meta_stream)
```
Please update Documenteer's YAML usage accordingly (assuming that doing so wouldn't cause a PyYAML version conflict, of course).

**Comment by timj** [comment]
Fixing this would be great.

**Comment by jonathansick** [comment]
In progress: https://jira.lsstcorp.org/browse/DM-22537

**Comment by kfindeisen** [comment]
My mistake; I didn't realize at the time that Jira had a `documenteer` component. Should we close the GitHub issue?

**Comment by jonathansick** [comment]
I'll close it when I merge the PR.
